-- MySQL Script generated by MySQL Workbench
-- 05/25/20 18:35:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema badapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `badapp` ;

-- -----------------------------------------------------
-- Schema badapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `badapp` DEFAULT CHARACTER SET utf8 ;
USE `badapp` ;

-- -----------------------------------------------------
-- Table `badapp`.`barrios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badapp`.`barrios` ;

CREATE TABLE IF NOT EXISTS `badapp`.`barrios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `badapp`.`localidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badapp`.`localidades` ;

CREATE TABLE IF NOT EXISTS `badapp`.`localidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `badapp`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badapp`.`eventos` ;

CREATE TABLE IF NOT EXISTS `badapp`.`eventos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(450) NULL DEFAULT NULL COMMENT '',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT '',
  `fecha_desde` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `fecha_hasta` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `barrios_id` INT(11) NOT NULL COMMENT '',
  `localidades_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_eventos_barrios1_idx` (`barrios_id` ASC)  COMMENT '',
  INDEX `fk_eventos_localidades1_idx` (`localidades_id` ASC)  COMMENT '',
  CONSTRAINT `fk_eventos_barrios1`
    FOREIGN KEY (`barrios_id`)
    REFERENCES `badapp`.`barrios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `badapp`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `badapp`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `badapp`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `badapp`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(250) NULL DEFAULT NULL COMMENT '',
  `rol` VARCHAR(250) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(250) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
